{% set name = "pytest-azurepipelines" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fd08f089bca0fad3c2b6fde9dbea69b975492ffaa8cb637cc987e64af8c18b9c

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv"

requirements:
  host:
    - python
    - pip
    - wheel
  run:
    - importlib_resources
    - python
    - pytest
    - pytest-nunit

test:
  imports:
    - pytest_azurepipelines
  requires:
    - pip
  commands:
    - pip check
    - "py.test --traceconfig | grep pytest-azurepipelines-{{ version }}"

about:
  home: https://github.com/tonybaloney/pytest-azurepipelines
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Plugin for pytest that makes it simple to work with Azure Pipelines'
  description: |
    Making Pytest easier to use with Microsoft Azure Pipelines. Just run pytest with
    this plugin and see your test results in the Azure Pipelines UI!
  doc_url: https://github.com/tonybaloney/pytest-azurepipelines
  dev_url: https://github.com/tonybaloney/pytest-azurepipelines

extra:
  recipe-maintainers:
    - leouieda
    - tonybaloney
