{% set name = "pytest-azurepipelines" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 225573ae479cb8f25d84b8d51c7e2bb037f9e89f35bf2950baad0b2385069506

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pytest

test:
  imports:
    - pytest_azurepipelines
  commands:
    - "py.test --traceconfig | grep pytest-azurepipelines-{{ version }}"

about:
  home: https://github.com/tonybaloney/pytest-azurepipelines
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Plugin for pytest that makes it simple to work with Azure Pipelines'

  description: |
    Making Pytest easier to use with Microsoft Azure Pipelines. Just run pytest with
    this plugin and see your test results in the Azure Pipelines UI!
  doc_url: https://github.com/tonybaloney/pytest-azurepipelines
  dev_url: https://github.com/tonybaloney/pytest-azurepipelines

extra:
  recipe-maintainers:
    - leouieda
    - tonybaloney
