travis:
  secure:
    BINSTAR_TOKEN: bU+MVyuTXkEXBgLrlmvSdIe3AK1CLuq6VXk26AfvVcJRcrREAbBLQxHY73yYoH0w9WPBSuNWwWL13ihnLpQpBUVi/w3VqIAUCGsmAKInwihpevSzHD8hvCPbkiblM3F9B/ruS9Fb72UDNIMdP8VwQcs0tTDdrRup2McNUafxci7n/d8Nt6n1r90psSjQFAtj4ZIMyfzpv8WUWXBc01k4g36j9SJ0Zgv7ECt42qXl43x1Ag6Jbi2mwCbR405dDyFjfWy+zPKaF0ASMXdz8zQlexNr4ZZUBMqVfwmKx3hkBqakBL5TrLv9w2NTvFw74c6zylYIVXU5pjPRnkRzRk052nrMtaaS05zyI033ZvN9za1ekcvfbuIQL8HSTIhHquc+h7tnVkaVzSeoInauQi9ZBGMpF0+4CvlnMw65SpkwbTdBD9mL5m1ShXYltUn9lrlME1knFfBdJVYYAwe1EADvNlnJsZO30BeP4uCQGZ9+3Foe8U2CgOdNu3PIMifNd4cvmQEpAzxdAC20+rnpWrrxmsaQXMM70UJmxdJv/dQs1fRfP5a5ETxAM75L5aON+uFa4cDcug5bm+RBCeOXtvFku51LMVDN1Gm6dAfrrsICr7qWngfxMjTSJuTZQdvxJdIl0KrL6+89ympFzxJmu7NIu4LxrXf55ftwPqipJPjbUEc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
